const dracFlowLyrics = [
    "This shit aint nothin to me man",
    "We smokin runtz",
    "I had to do it to them snipe",
    "Shorty chose to be with a demon",
    "This shit aint nothin to me man",
    "This shit aint nothing to me man",
    "This shit aint nothin to me man",
    "Im nice with it haha",
    "My money long my pockets deep",
    "No pocket watchin in these parts",
    "Chanel optics got me seein shit",
    "This shit aint nothin to me man",
    "This shit aint nothin to me man",
    "Chanel optics got mе seein shit",
    "I need fentanyl slime",
    "Yall cant fuck with me",
    "That coochie yummy slime",
    "This shit aint nothin to me man",
    "Can you remind me who I am?",
    "Hello? Blac Chyna?",
    "Im movin different",
    "We smokin dung beetle",
    "Im on them Georgetown Gеronimos",
    "Im on them Nashville nibblers",
    "I dont give a fuck if I go blind",
    "Ill fuckin kill you",
    "This shit aint nothin to me man",
    "Im movin like Oppenheimer",
    "Cause I dont give a shit",
    "This shit aint nothin to me man",
    "This shit aint nothin to me man",
    "I got Midas touch fuck boy",
    "I gave that pussy a raspberry",
    "They will not find me",
    "Konichiwa you little jit",
    "I aint never going back",
    "Glock-34 shivered his timbers",
    "They said I wouldnt shit on em",
    "Hashtag: \"Le Chemin du Roi\"",
    "I keep my Glock at the Vatican",
    "\"Him-buktu\" \"Him-on and Pumba\"",
    "I got my DNA test back",
    "Fuck it I ate the opp",
    "She let me hit it",
    "That gash sound like salmon roe",
    "You ran off with the Diddy Kong",
    "Triple espresso",
    "Icewear Vezzo said it best",
    "\"Im a mud baby I cant stop\"",
    "Fuck it",
    "Im coming for every enzyme",
    "Snorting dexie",
    "Turned his city into Pompeii",
    "Im moving lucrative",
    "Im in the pod smoking Sebulba",
    "Im on the Ivory Coast eating",
    "Vermilion snapper",
    "War is all I think about",
    "This shit aint nothing to me man",
    "I need my percs!",
    "I need my percs!",
    "One perc is never enough (Yo!)",
    "[Growls]",
    "Im doing a lot of drugs a lot!",
    "For forty days and forty nights",
    "And a fifth of henny",
    "I really do this shit",
    "What the fuck is Obamacare?",
    "Look at this shit",
    "I sold crack to myself",
    "We smoking that Boomhauer",
    "Im smoking lizard taint",
    "Sniffing monkey",
    "[Screams]",
    "Im getting too much money!",
    "Broke boy wasnt balling enough",
    "Welcome to the Guangdong Tigers",
    "These Ferragamos are real cunt",
    "Popped four flim-flams at K.O.D.",
    "Came out with Hepatitis",
    "Ill fucking kill you!",
    "The first time I smoked runts",
    "I coughed so fucking hard",
    "I started passing kidney stones",
    "Everybody has an asshole",
    "Most people have dick and balls",
    "Go outside and get a bag!",
    "I knew the perc was fake",
    "Crash the Benz truck",
    "Sip some mud",
    "Everything felt alright",
    "Yeah I drill with my mask off",
    "Im moving like Gilbert Arenas",
    "Sniffing white phosphorus",
    "Im a real creature",
    "Ill spin the block",
    "Huffing spores",
    "To see tomorrows stock market",
    "Lungs looking crazy",
    "Boy ran off with a Banjo-Kazooie",
    "Every puff is an insult to God",
    "This zaza will give you a 2019",
    "Alex Caruso hairline",
    "Chopper small and sturdy",
    "Built like Wilmer Valderrama",
    "Then euthanize herself",
    "Trackhawk sound like Game Seven",
    "Yahoo!",
    "Ill give you that fluoride stare",
    "This henny got me feeling crazy",
    "Drank man please!",
    "Im thirsty!",
    "Im ready Im trying to po up",
    "Drank man please!",
    "And do something crazy",
    "crocodile egg shaman gelato",
    "I went dark a long time ago",
    "Money longer than KDs feet",
    "I fuck like its for survival",
    "Sipping on McDonalds house red",
    "They asked me to shoot I do it",
    "I have no character",
    "Payton Manning",
    "Im a street creature",
    "Over and over and over again",
    "Im a product of the gutter",
    "Im the real goliath grouper",
    "This blunt has a pulse",
    "A big meaty piece of shit",
    "Husky little fella",
    "The bugs are back",
    "Im smoking on pussy slaw",
    "I got this shit figured out",
    "This is an army of two",
    "He look like Bandman Kevo now",
    "The bugs are back",
    "I dont wanna kill them shut up!",
    "I dont wanna kill anybody!",
    "Put the gun down young man",
    "We are indeed close",
    "Im a high functioning shooter",
    "Yeah Im big on astrology",
    "Pussy clot",
    "I need to kill!",
    "I need to kill!",
    "Give me the fucking fentanyl",
    "This shit is international",
    "Im a real glutton",
    "Ahh!",
    "Wa-chow!",
    "Mustard on the beat ho",
    "But we all know Im fucking not",
    "Im fucked",
    "Im ready to change",
    "Whoa Dexter!",
    "Im thankful for it",
    "Pistol built like Dave Portnoy",
    "Im so busy shooting Im celibate",
    "Im moving like Meek Mill",
    "Didnt drink any water all day",
    "Use your fucking head",
    "I come from nothing",
    "I started this shit",
    "Im psycho",
    "Im a real shit-flinging beast",
    "Fuck!",
    "We smoking bile",
    "Were getting warmer",
    "How you feel gang?",
    "She eating my ass and whatnot",
    "Im a fucking mud slut",
    "Im sick! Ahh the worms!",
    "Im moving the needle",
    "Tyga?",
    "Ah the worms are back",
    "Ahhh! The worms are back!",
    "That perc eating my ass up",
    "Then she shitted on my seat",
    "I dont give a shit",
    "Shitception",
    "I want to watch you burn",
    "Im moving crazy",
    "Flexible on the Fentanyl",
    "We smoking shit we smoking rock",
    "I got exotic zaza man please",
    
];

module.exports = { dracFlowLyrics }